### ISSUE TITLE
Ubuntu 16.104 LST compilation Error

### ISSUE THREAD

**Issue by Spacial** [cascremers/scyther#16]
cloning the repo and installing the packages required for ubuntu 16.04 (fresh install), still not compiling scynther:

ubuntu@ubuntuFA:~/scyther/src$ make clean
ubuntu@ubuntuFA:~/scyther/src$ ./build.sh 
/usr/bin/env: “python”: Arquivo ou diretório não encontrado
Linux
-- Found Flex: /usr/bin/flex
-- Found Bison: /usr/bin/bison
-- Locating platform specific file BuildUnix.cmake
-- Building Linux version
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/scyther/src
[  2%] Building scanner.c from scanner.l using flex
[  5%] Building parser.c from parser.y using bison
Scanning dependencies of target scyther-linux
[  7%] Building C object CMakeFiles/scyther-linux.dir/arachne.o
[ 10%] Building C object CMakeFiles/scyther-linux.dir/binding.o
[ 12%] Building C object CMakeFiles/scyther-linux.dir/claim.o
[ 15%] Building C object CMakeFiles/scyther-linux.dir/color.o
[ 17%] Building C object CMakeFiles/scyther-linux.dir/compiler.o

you need to include the python-minimal package on requirements:

ubuntu@ubuntuFA:~/scyther/src$ grep -rni python *
describe-version.py:1:#!/usr/bin/env python
find-unused-functions.py:1:#!/usr/bin/python
regression-tests/regression-test.py:1:#!/usr/bin/env python
scantags.py:1:#!/usr/bin/python

after that, it compiles flawlessly

 ./build.sh 
v1.1.3-18-g5103876
Linux
-- Found Flex: /usr/bin/flex
-- Found Bison: /usr/bin/bison
-- Locating platform specific file BuildUnix.cmake
-- Building Linux version
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/scyther/src
[  2%] Building scanner.c from scanner.l using flex
[  5%] Building parser.c from parser.y using bison
Scanning dependencies of target scyther-linux
[  7%] Building C object CMakeFiles/scyther-linux.dir/arachne.o
[ 10%] Building C object CMakeFiles/scyther-linux.dir/binding.o
[ 12%] Building C object CMakeFiles/scyther-linux.dir/claim.o
[ 15%] Building C object CMakeFiles/scyther-linux.dir/color.o
[ 17%] Building C object CMakeFiles/scyther-linux.dir/compiler.o
[ 20%] Building C object CMakeFiles/scyther-linux.dir/cost.o
[ 22%] Building C object CMakeFiles/scyther-linux.dir/debug.o
[ 25%] Building C object CMakeFiles/scyther-linux.dir/depend.o
[ 27%] Building C object CMakeFiles/scyther-linux.dir/dotout.o
[ 30%] Building C object CMakeFiles/scyther-linux.dir/error.o
[ 32%] Building C object CMakeFiles/scyther-linux.dir/heuristic.o
[ 35%] Building C object CMakeFiles/scyther-linux.dir/hidelevel.o
[ 37%] Building C object CMakeFiles/scyther-linux.dir/intruderknowledge.o
[ 40%] Building C object CMakeFiles/scyther-linux.dir/knowledge.o
[ 42%] Building C object CMakeFiles/scyther-linux.dir/label.o
[ 45%] Building C object CMakeFiles/scyther-linux.dir/list.o
[ 47%] Building C object CMakeFiles/scyther-linux.dir/main.o
[ 50%] Building C object CMakeFiles/scyther-linux.dir/mgu.o
[ 52%] Building C object CMakeFiles/scyther-linux.dir/prune_bounds.o
[ 55%] Building C object CMakeFiles/scyther-linux.dir/prune_theorems.o
[ 57%] Building C object CMakeFiles/scyther-linux.dir/role.o
[ 60%] Building C object CMakeFiles/scyther-linux.dir/specialterm.o
[ 62%] Building C object CMakeFiles/scyther-linux.dir/states.o
[ 65%] Building C object CMakeFiles/scyther-linux.dir/switches.o
[ 67%] Building C object CMakeFiles/scyther-linux.dir/symbol.o
[ 70%] Building C object CMakeFiles/scyther-linux.dir/system.o
[ 72%] Building C object CMakeFiles/scyther-linux.dir/tac.o
[ 75%] Building C object CMakeFiles/scyther-linux.dir/tempfile.o
[ 77%] Building C object CMakeFiles/scyther-linux.dir/termlist.o
[ 80%] Building C object CMakeFiles/scyther-linux.dir/termmap.o
[ 82%] Building C object CMakeFiles/scyther-linux.dir/term.o
[ 85%] Building C object CMakeFiles/scyther-linux.dir/timer.o
[ 87%] Building C object CMakeFiles/scyther-linux.dir/type.o
[ 90%] Building C object CMakeFiles/scyther-linux.dir/warshall.o
[ 92%] Building C object CMakeFiles/scyther-linux.dir/xmlout.o
[ 95%] Building C object CMakeFiles/scyther-linux.dir/parser.o
[ 97%] Building C object CMakeFiles/scyther-linux.dir/scanner.o
[100%] Linking C executable scyther-linux
[100%] Built target scyther-linux

---------------------------------------------------------
Built the Linux binary
Copied the file to the gui/Scyther directory and ~/bin
---------------------------------------------------------

**Comment by cascremers** [comment]
Thanks, this is now solved by commit 1c278ca4274307452b403cb3689e0a06e7fb00d2 in `master` with the same patch applied in the `compromising adversaries` branch.

This will propagate into the stable packages soon.
