### ISSUE TITLE
Python 2 is deprecated

### ISSUE THREAD

**Issue by pyropeter** [cascremers/scyther#20]
For this to work after 31.12.2019 without significant effort, it needs to be ported to Python 3.

https://pythonclock.org/

**Comment by cascremers** [comment]
This is finally being tackled in the `python3-wxpython4` branch, to be released soon (I hope).

**Comment by Infinisil** [comment]
Is this work still ongoing? Otherwise scyther will be removed from the nixpkgs package collection for now (see above PR)

**Comment by cascremers** [comment]
We work is actually completed in a branch, but didn't find time yet for proper release.

**Comment by cascremers** [comment]
Released a while ago, should all work now since v1.2 (2411493).
