### ISSUE TITLE
One role per agent does not work

### ISSUE THREAD

**Issue by Mofo50C** [cascremers/scyther#38]
**Describe the bug**
The backend option --one-role-per-agent does nothing.

**To Reproduce**
1. Open GUI
2. Go to settings
3. Paste in --one-role-per-agent for backend arguments
4. Run verify on protocol
5. Attacks still show agents assuming multiple roles

**Expected behavior**
Use this protocol and verify the claim(I, Commit, R, Kir) https://gist.github.com/Mofo50C/31246287024580ab24283c559f7887fd

**Scyther version used:**
 - backend version: v1.2-25-g2a698fa
 - GUI version is compiled from master, but it doesn't show which version

**Platform information (please complete the following information):**
 - OS: Ubuntu 20.04 running on WSL2 on Windows 10
 - Running python 3.8 and wxPython 4.2.1

**Comment by cascremers** [comment]
Please add a picture here of the attacks. (When I try this, none of the generated attacks contain an agent that executes multiple roles.)

**Comment by Mofo50C** [comment]
Hi there, this is what i get for I's claim on commit R
![image](https://github.com/cascremers/scyther/assets/21063744/afe49284-f452-4c62-bfca-c601b2164fee)
![image](https://github.com/cascremers/scyther/assets/21063744/e0fcb354-6f0f-49a1-a169-c287069742a4)

**Comment by Mofo50C** [comment]
I've tried it with option "--one-role-per-agent"; in the actual protocol and --one-role-per-agent in the backend arguments. With 5 runs and best attack.

**Comment by cascremers** [comment]
In your image, there are two agents, and they each perform a different role. This is matches the requirements for the "one role per agent" switch.

Perhaps your concern is that Alice (when executing the I role), upon receiving the message, assumes that Alice is also performing the R role -- but this is only a variable instantiation, and does not imply Alice plays both roles. If the protocol has no explicit checks to exclude this behavior, then this is typically possible.

In any case, I think this is not a bug report, but rather a misunderstanding of the "one role per agent" restriction, which is met here.

**Comment by Mofo50C** [comment]
Oh I see, after playing around with the settings, i came across the following attack that is what i thought would be shown with the "one role per agent" argument.
![image](https://github.com/cascremers/scyther/assets/21063744/9dc8c3aa-4aba-4ef0-bb09-fc758a4f7434)
